version: '3'

services:

  webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    env_file: .env
    restart: always
    ports:
      - "${AIRFLOW_PORT}:8080"
    volumes:
      - airflow:/var/workflow_output
      - ./openverse_catalog:/usr/local/airflow/openverse_catalog

volumes:
  airflow:
